### ISSUE TITLE
Skyhawk Kerbalism Roadmap

### ISSUE THREAD

**Issue by CessnaSkyhawk** [CessnaSkyhawk/SkyhawkKerbalism#1]
**Science Experiments**
- [x] #2
- [ ] #3
- [x] #4
- [ ] #5
- [x] #6
- [ ] #7
- [x] #8
- [ ] #9
- [x] #10
- [ ] #11
- [x] #12
- [ ] #13
- [x] #14
- [ ] #15
- [x] #16
- [ ] #18
- [x] #19
- [x] #20
- [x] #21
- [x] #22
- [x] #23

**Mod Support**
- [ ] LS Support
- [ ] Science Support
- [ ] Hard Drive Support

**Planet Pack Support**
- [ ] LS Time Support
- [ ] Science Time Support
- [ ] Radiation Support
